<?php

namespace NikunjKothiya\QueueMonitor\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use NikunjKothiya\QueueMonitor\Models\QueueFailure;

class QueueFailureNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        protected QueueFailure $failure
    ) {
        //
    }

    public function via(mixed $notifiable): array
    {
        $channels = [];

        if (config('queue-monitor.alerts.mail_to') || config('mail.from.address')) {
            $channels[] = 'mail';
        }

        // Note: Slack is handled separately via webhook in AlertDispatchService
        // This notification only handles email

        return $channels;
    }

    public function toMail(mixed $notifiable): MailMessage
    {
        $url = route('queue-monitor.failures.show', $this->failure);
        $priorityLabel = $this->failure->getPriorityLabel();
        $priorityColor = match($priorityLabel) {
            'Critical' => '#dc3545',
            'High' => '#fd7e14',
            'Medium' => '#ffc107',
            default => '#6c757d',
        };

        return (new MailMessage())
            ->subject("[{$priorityLabel}] Queue Failure: " . $this->failure->job_name)
            ->greeting('Queue Job Failed')
            ->line("**Environment:** {$this->failure->environment}")
            ->line("**Job:** {$this->failure->job_name}")
            ->line("**Queue:** " . ($this->failure->queue ?? 'default'))
            ->line("**Connection:** " . ($this->failure->connection ?? 'default'))
            ->line("**Exception:** " . class_basename($this->failure->exception_class))
            ->line("**Message:** " . $this->truncate($this->failure->exception_message, 500))
            ->line("**Failed At:** " . $this->failure->failed_at?->toDateTimeString())
            ->action('View Failure Details', $url)
            ->line('---')
            ->line('This notification was generated by Laravel Queue Monitor.');
    }
    
    /**
     * Truncate a string to specified length.
     */
    protected function truncate(string $text, int $length): string
    {
        if (strlen($text) <= $length) {
            return $text;
        }
        
        return substr($text, 0, $length) . '...';
    }
}


