<?php

namespace NikunjKothiya\QueueMonitor\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Messages\SlackMessage;
use Illuminate\Notifications\Notification;
use NikunjKothiya\QueueMonitor\Models\QueueFailure;

class QueueFailureNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        protected QueueFailure $failure
    ) {
        //
    }

    public function via(mixed $notifiable): array
    {
        $channels = [];

        if (config('queue-monitor.alerts.mail_to') || config('mail.from.address')) {
            $channels[] = 'mail';
        }

        if (config('queue-monitor.alerts.slack_webhook_url')) {
            $channels[] = 'slack';
        }

        return $channels;
    }

    public function toMail(mixed $notifiable): MailMessage
    {
        $url = route('queue-monitor.failures.show', $this->failure);

        return (new MailMessage())
            ->subject('Queue Failure: ' . $this->failure->job_name)
            ->line('A queue job has failed in environment: ' . $this->failure->environment)
            ->line('Job: ' . $this->failure->job_name)
            ->line('Exception: ' . $this->failure->exception_message)
            ->action('View Failure', $url)
            ->line('This notification was generated by Laravel Queue Monitor.');
    }

    public function toSlack(mixed $notifiable): SlackMessage
    {
        $url = route('queue-monitor.failures.show', $this->failure);

        return (new SlackMessage())
            ->error()
            ->content('A queue job has failed in ' . $this->failure->environment)
            ->attachment(function ($attachment) use ($url) {
                $attachment
                    ->title($this->failure->job_name, $url)
                    ->fields([
                        'Queue' => $this->failure->queue ?? '-',
                        'Connection' => $this->failure->connection ?? '-',
                        'Exception' => $this->failure->exception_message,
                        'Failed At' => optional($this->failure->failed_at)->toDateTimeString(),
                    ]);
            });
    }
}


